# Generated by Django 5.1 on 2024-08-22 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernorte', '0002_remove_lernort_bild1_remove_lernort_bild2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='lernort',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='lernorte.lernort'),
        ),
    ]
